# Generated by Django 3.1.6 on 2023-08-30 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='about_us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', froala_editor.fields.FroalaField(default='')),
                ('description_am', froala_editor.fields.FroalaField(default='')),
                ('description_en', froala_editor.fields.FroalaField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(default='', max_length=70)),
                ('name_am', models.CharField(default='', max_length=70)),
                ('name_en', models.CharField(default='', max_length=70)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('blog_id', models.TextField(default='')),
                ('description_arm', froala_editor.fields.FroalaField(default='')),
                ('description_rus', froala_editor.fields.FroalaField(default='')),
                ('description_eng', froala_editor.fields.FroalaField(default='')),
                ('avatar_p', models.FileField(default='', upload_to='')),
                ('video', models.FileField(default='', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='', max_length=20)),
                ('brand_picture', django_resized.forms.ResizedImageField(crop=None, default='', force_format='WEBP', keep_meta=False, quality=70, scale=None, size=[1920, 1080], upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='category_choeses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_en', models.CharField(default='', max_length=50)),
                ('name_am', models.CharField(default='', max_length=50)),
                ('category_id', models.CharField(default='', max_length=7)),
                ('category_id_main', models.CharField(default='', max_length=14)),
                ('products_count', models.PositiveIntegerField(default=0)),
                ('image', models.FileField(default='', upload_to='')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='store.category_choeses')),
            ],
        ),
        migrations.CreateModel(
            name='checkout_products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mass', models.PositiveIntegerField(default='0')),
                ('price', models.CharField(default='', max_length=6)),
                ('transaction_id', models.CharField(default='', max_length=12)),
                ('status', models.CharField(default='', max_length=10)),
                ('assembled', models.CharField(default='notassembled', max_length=20)),
                ('order_id', models.CharField(default='', max_length=7)),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('comments', models.CharField(default='', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='counter_props',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter_name', models.CharField(default='', max_length=50)),
                ('counter_prop', models.CharField(default='', max_length=50)),
                ('counter_price', models.CharField(default='', max_length=50)),
                ('counter_price_sale', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='delivery_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', froala_editor.fields.FroalaField(default='')),
                ('description_am', froala_editor.fields.FroalaField(default='')),
                ('description_en', froala_editor.fields.FroalaField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='home_slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_id', models.CharField(default='', max_length=1)),
                ('image', django_resized.forms.ResizedImageField(crop=None, default='', force_format='WEBP', keep_meta=True, quality=80, scale=None, size=[1920, 1080], upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='mass_props',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mass_name', models.CharField(default='', max_length=50)),
                ('mass_prop', models.CharField(default='', max_length=50)),
                ('mass_price', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='max_cart_price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default='0')),
            ],
        ),
        migrations.CreateModel(
            name='my_contacts_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=30)),
                ('email', models.CharField(default='', max_length=30)),
                ('phone_number', models.CharField(default='', max_length=20)),
                ('country', models.CharField(default='', max_length=12)),
                ('state', models.CharField(default='', max_length=12)),
                ('city', models.CharField(default='', max_length=12)),
                ('address', models.CharField(default='', max_length=35)),
                ('index', models.CharField(default='', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='order_id_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default='', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='price_of_deliverybox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mass_start', models.PositiveIntegerField(default='0')),
                ('mass_end', models.PositiveIntegerField(default='0')),
                ('total_mass', models.PositiveIntegerField(default='0')),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(default='', max_length=50)),
                ('name_am', models.CharField(default='', max_length=50)),
                ('name_en', models.CharField(default='', max_length=50)),
                ('product_id', models.TextField(default='')),
                ('description_arm', models.CharField(default='', max_length=400)),
                ('description_rus', models.CharField(default='', max_length=400)),
                ('description_eng', models.CharField(default='', max_length=400)),
                ('sale', models.FloatField(blank=True, default=0, null=True)),
                ('sale_price', models.FloatField(blank=True, default=0, null=True)),
                ('mass', models.CharField(default='', max_length=6)),
                ('category', models.CharField(default='', max_length=40)),
                ('size', models.CharField(default='', max_length=30)),
                ('pcs_type', models.CharField(default='', max_length=5)),
                ('price', models.FloatField(blank=True, default='0', null=True)),
                ('pcs', models.CharField(default='', max_length=10)),
                ('color', models.CharField(default='', max_length=50)),
                ('active', models.BooleanField(default=False)),
                ('color_id', models.CharField(default='', max_length=50)),
                ('SKU_code', models.CharField(default='', max_length=20)),
                ('min_size', models.PositiveIntegerField(default=0)),
                ('max_size', models.PositiveIntegerField(default=0)),
                ('size_pcs', models.PositiveIntegerField(default=0)),
                ('price_pcs', models.PositiveIntegerField(default=0)),
                ('price_size', models.PositiveIntegerField(default=0)),
                ('sale_price_size', models.PositiveIntegerField(default=0)),
                ('sale_price_pcs', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('view_s', models.PositiveIntegerField(default='0')),
                ('avatar_p', django_resized.forms.ResizedImageField(crop=None, default='', force_format='WEBP', keep_meta=False, quality=75, scale=None, size=[400, 400], upload_to='')),
                ('video', models.FileField(default='', upload_to='')),
                ('video_link', models.CharField(default='', max_length=100)),
                ('zoom_image', django_resized.forms.ResizedImageField(crop=None, default='', force_format='WEBP', keep_meta=True, quality=70, scale=None, size=[1920, 1080], upload_to='')),
                ('product_status', models.CharField(default='', max_length=150)),
                ('prop', models.PositiveIntegerField(default='0')),
                ('prop_type', models.CharField(default='', max_length=5)),
                ('Brand', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Brand_rel', to='store.brand')),
                ('category_choeses', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_choeses_product', to='store.category_choeses')),
                ('counter_props', models.ManyToManyField(to='store.counter_props')),
            ],
        ),
        migrations.CreateModel(
            name='products_cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default='0')),
                ('count_size', models.PositiveIntegerField(default='0')),
                ('price', models.FloatField(default='0')),
                ('indicator', models.CharField(max_length=10, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_productss', to='store.products')),
            ],
        ),
        migrations.CreateModel(
            name='products_commets_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(default='', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='products_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False)),
                ('transaction_id', models.CharField(max_length=10, null=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('count_size', models.PositiveIntegerField(default=0)),
                ('price', models.FloatField(default='0')),
                ('indicator', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=30)),
                ('last_name', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(default='none@email.com', max_length=254)),
                ('birth_date', models.DateField(default='1999-12-31')),
                ('city', models.CharField(default='', max_length=40)),
                ('state', models.CharField(default='', max_length=50)),
                ('country', models.CharField(default='', max_length=50)),
                ('receiver', models.CharField(default='', max_length=100)),
                ('phone_number', models.CharField(default='', max_length=20)),
                ('zipcode', models.CharField(default='', max_length=10)),
                ('checkout_products_list', models.ManyToManyField(related_name='products_Orders', to='store.products_Order')),
                ('product_cart', models.ManyToManyField(related_name='product_cart_c', to='store.products_cart')),
            ],
        ),
        migrations.CreateModel(
            name='rates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_name', models.CharField(max_length=3)),
                ('rate', models.FloatField(default=1)),
                ('date_updates', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='rules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', froala_editor.fields.FroalaField(default='')),
                ('description_am', froala_editor.fields.FroalaField(default='')),
                ('description_en', froala_editor.fields.FroalaField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='sizes_props',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_name', models.CharField(default='', max_length=50)),
                ('size_prop', models.CharField(default='', max_length=50)),
                ('size_price', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='sub_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descendant', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('category_deg', models.PositiveIntegerField(default='0')),
                ('products_count', models.PositiveIntegerField(default='0')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visits', models.PositiveIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='zone_countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_number', models.PositiveIntegerField(default='0')),
                ('zone_countries', models.ManyToManyField(related_name='zone_countries_many', to='store.zone_countries')),
            ],
        ),
        migrations.CreateModel(
            name='shipping_address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('zipcode', models.CharField(default='', max_length=10)),
                ('res_name', models.CharField(default='', max_length=80)),
                ('Country', models.CharField(default='', max_length=20)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Store_shipping_address', to='store.profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='shipping_address',
            field=models.ManyToManyField(related_name='shipping_address', to='store.shipping_address'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='productsimage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_e', django_resized.forms.ResizedImageField(crop=None, default='', force_format='WEBP', keep_meta=True, quality=70, scale=None, size=[1920, 1080], upload_to='')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productsimages', to='store.products')),
            ],
        ),
        migrations.AddField(
            model_name='products_order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Products_orders', to='store.profile'),
        ),
        migrations.AddField(
            model_name='products_order',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_product', to='store.products'),
        ),
        migrations.AddField(
            model_name='products_order',
            name='shipping_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_contacts_info_order', to='store.my_contacts_info'),
        ),
        migrations.CreateModel(
            name='products_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('stars', models.PositiveIntegerField(default='0')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_comment', to='store.products')),
                ('products_commets_images', models.ManyToManyField(related_name='products_commets_images', to='store.products_commets_images')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_pro', to='store.profile')),
            ],
        ),
        migrations.AddField(
            model_name='products_cart',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_product_cart', to='store.profile'),
        ),
        migrations.AddField(
            model_name='products',
            name='sizes_props',
            field=models.ManyToManyField(to='store.sizes_props'),
        ),
        migrations.AddField(
            model_name='products',
            name='sub_categories',
            field=models.ManyToManyField(to='store.category_choeses'),
        ),
        migrations.AddField(
            model_name='my_contacts_info',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_info_profile', to='store.profile'),
        ),
        migrations.CreateModel(
            name='Mass_and_money',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mass_start', models.PositiveIntegerField(default='0')),
                ('mass_end', models.PositiveIntegerField(default='0')),
                ('money', models.FloatField(default='0')),
                ('type', models.CharField(default='', max_length=15)),
                ('zones', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zone_class', to='store.zone')),
            ],
        ),
        migrations.CreateModel(
            name='favorite_products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default='0')),
                ('count_size', models.PositiveIntegerField(default='0')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_features', to='store.products')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_features', to='store.profile')),
            ],
        ),
        migrations.CreateModel(
            name='delivery_check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('mass', models.FloatField(default=0)),
                ('pay_status', models.CharField(default='dontpay', max_length=15)),
                ('order_id', models.CharField(default='', max_length=7)),
                ('my_contacts_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_contacts_info', to='store.my_contacts_info')),
            ],
        ),
        migrations.CreateModel(
            name='day_of_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_day', to='store.products')),
            ],
        ),
        migrations.CreateModel(
            name='collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_name', models.CharField(default='', max_length=25)),
                ('mass', models.FloatField(default=0)),
                ('checkout_products', models.ManyToManyField(blank=True, null=True, related_name='checkout_products_many', to='store.checkout_products')),
                ('delivery_check', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_check_collection', to='store.delivery_check')),
                ('orders', models.ManyToManyField(related_name='products_Order_many', to='store.products_Order')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_collection', to='store.profile')),
            ],
        ),
        migrations.AddField(
            model_name='checkout_products',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_Order', to='store.collection'),
        ),
        migrations.AddField(
            model_name='checkout_products',
            name='delivery_check',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_check', to='store.delivery_check'),
        ),
        migrations.AddField(
            model_name='checkout_products',
            name='my_contacts_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_contacts_info_check', to='store.my_contacts_info'),
        ),
        migrations.AddField(
            model_name='checkout_products',
            name='products_Order',
            field=models.ManyToManyField(related_name='products_Order', to='store.products_Order'),
        ),
        migrations.AddField(
            model_name='checkout_products',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_Order', to='store.profile'),
        ),
    ]
