# Generated by Django 3.1.6 on 2023-09-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='visits_one_day',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
