# Generated by Django 3.1.6 on 2023-09-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20230901_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='visits_last',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
