# Generated by Django 3.1.6 on 2023-09-07 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20230907_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products_order',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_product', to='store.products'),
        ),
        migrations.AlterField(
            model_name='products_order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_contacts_info_order', to='store.my_contacts_info'),
        ),
    ]
