# Generated by Django 3.1.6 on 2023-09-07 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20230907_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout_products',
            name='my_contacts_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_contacts_info_check', to='store.my_contacts_info'),
        ),
        migrations.AlterField(
            model_name='delivery_check',
            name='my_contacts_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_contacts_info', to='store.my_contacts_info'),
        ),
    ]
